postgres: &postgres
  adapter: postgresql
  encoding: unicode
  database: dwh_scharles
  host: localhost
  pool: 5
  username: codeboxx
  password: Codeboxx!

development:
  <<: *postgres
  database: dwh_scharles