postgres: &postgres
  adapter: postgresql
  encoding: unicode
  database: postgres
  host: localhost
  pool: 5
  username: postgres
  password: ines2010

development:
  <<: *postgres
  database: postgres