postgres: &postgres
  adapter: postgresql
  encoding: unicode
  database: rocketelevators_development
  host: localhost
  pool: 5
  username: postgres
  password: password

development:
  <<: *postgres
  database: rocketelevators_development